### PR TITLE
Update executors to 5.5.*

### PR DESCRIPTION
**Pull request by peterguy**
Including the Docker Mirror executor.

### Test plan

N/A

### CODE REVIEW

**Comment by loujar** [comment]
@peterguy there are some [other references](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/sourcegraph/terraform-aws-executors%24+5.3&patternType=keyword&sm=0) to the 5.3 version throughout this repo (specifically across the `README.md` files and in the `examples` directory) which I think we should update along with the actual TF script changes.

Also, are we preparing a similar PR for `terraform-google-executors`?

**Review by loujar — COMMENTED** [review]
[This PR](https://github.com/sourcegraph/terraform-aws-executors/pull/99) could be a good guide for what we should probably update for the bump up to 5.5

**Comment by peterguy** [comment]
Thanks @loujar; I’ll take another pass.  Appreciate the reference PR. There is indeed another PR for Google executors. I’ll post the link once I get back to the keyboard.

**Comment by Chickensoupwithrice** [comment]
Hey team, I'm closing this PR now. We're up to `5.7.0` and we now merge the pull requests generated by the release, which should cover updating all the references to the older versions. If it doesn't, it's considered a bug and we'll look into resolving it!

**Pull request closed without merging**
