### PR TITLE
fix(executors): provide non-randomized template name

### LINKED ISSUE #79: creating EC2 Launch Template Version: InvalidTagSpecification.Malformed: The tags cannot be null or empty.
When:

```hcl
randomize_resource_names = false
```

The following error is seen in Terraform:

```bash
│ Error: creating EC2 Launch Template (ID) Version: InvalidTagSpecification.Malformed: The tags cannot be null or empty.
│       status code: 400, request id: ID
│
│   with module.sourcegraph-stg.module.executors-batches.aws_launch_template.executor,
│   on .terraform/modules/sourcegraph-stg.executors-batches/modules/executors/main.tf line 173, in resource "aws_launch_template" "executor":
│  173: resource "aws_launch_template" "executor" {
```

It appears to come from one of these 2 tag lines - https://github.com/sourcegraph/terraform-aws-executors/blob/e979d49da0a978a5d69a0a756200a5b66da0b6d8/modules/executors/main.tf#L246

As the value of `name` is set to `null` here - https://github.com/sourcegraph/terraform-aws-executors/blob/e979d49da0a978a5d69a0a756200a5b66da0b6d8/modules/executors/main.tf#L16

### PR DESCRIPTION
**Pull request by hutson**
Provide non-randomized template name so that Terraform can successfully create a Launch Template, which requires a non-null value as the value for tags using the template name property.

Fixes #79

### Test plan

What it looks like to create Batches executors with the fix compared to Codeintel executors without the fix (Diff truncated to relevant properties):

```bash
  # module.sourcegraph-stg.module.executors-batches.aws_launch_template.executor will be created
  + resource "aws_launch_template" "executor" {
      + name_prefix                          = "batches_sourcegraph_executor-template-"
      + tags                                 = {
          + "Name" = "batches_sourcegraph_executors"
        }
      + tags_all                             = {
          + "Name"                   = "batches_sourcegraph_executors"
          + "env"                    = "stg"
        }

    }

  # module.sourcegraph-stg.module.executors-codeintel.aws_launch_template.executor will be created
  + resource "aws_launch_template" "executor" {
      + name_prefix                          = "codeintel_sourcegraph_executor-template-"
      + tags_all                             = {
          + "env"                    = "stg"
        }
    }
```

^ The `Name` tag does not appear at all I believe because the value is `null`.

Targeted `apply` successfully creates the modified executors for the batches module:

```bash
$ terraform apply -target=module.sourcegraph-stg.module.executors-batches

...

Apply complete! Resources: 12 added, 0 changed, 0 destroyed.
```

Targeted `apply` of unmodified executors for codeintel fails as expected:

```bash
$ terraform apply -target=module.sourcegraph-stg.module.executors-codeintel

│ Error: creating EC2 Launch Template (codeintel_sourcegraph_executor-template-20230613161046219800000003): InvalidTagSpecification.Malformed: The tags cannot be null or empty.
│       status code: 400, request id: ID
│
│   with module.sourcegraph-stg.module.executors-codeintel.aws_launch_template.executor,
│   on .terraform/modules/sourcegraph-stg.executors-codeintel/modules/executors/main.tf line 173, in resource "aws_launch_template" "executor":
│  173: resource "aws_launch_template" "executor" {
```

### CODE REVIEW

**Comment by sanderginn** [comment]
Thanks for catching this!

Did you by any chance deploy the networking module too? I see we use a similar pattern of using `null` values for non-randomized `Name` tags in there (as well as a few other places), so I'm wondering if those should be updated with some string default as well, or if you didn't run into any issues when planning that module. Could very well be that AWS is being inconsistent with this policy though.

Either way I'll make sure to polish this PR if need be. Appreciate the contribution! 🙌

**Comment by hutson** [comment]
@sanderginn we do not use the networking, credentials, or docker modules. Our team has no control over IAM users or VPCs/Subnets.

Therefore we have to instantiate an executor module and pass in the VPC and Subnet allocated in our account by our company's cloud team:

```
module "executors-batches" {
  source                              = "sourcegraph/executors/aws//modules/executors"
  version                             = "v5.0.1"
  machine_type                        = "m6a.large"
  boot_disk_size                      = 20
  instance_tag                        = "batches"
  ssh_access_cidr_range               = "${var.private_ip}/32"
  sourcegraph_external_url            = var.fqdn
  sourcegraph_executor_proxy_password = jsondecode(data.aws_secretsmanager_secret_version.executor-token.secret_string)["sourcegraph-executor-token"]
  queue_name                          = "batches"
  maximum_num_jobs                    = 2 # Split instance in half for `job_*` variables.
  metrics_environment_label           = var.env
  job_num_cpus                        = 1
  job_memory                          = "4GB"
  use_firecracker                     = false
  max_replicas                        = 2
  docker_registry_mirror              = "docker.example.com"
  assign_public_ip                    = false
  resource_prefix                     = "batches"
  randomize_resource_names            = false
  permissions_boundary_arn            = "arn:aws:iam::${var.account}:policy/devops-iam-boundary"
  subnet_id                           = var.subnet_id
  vpc_id                              = var.vpc_id
}
```

**Comment by sanderginn** [comment]
Alright, thanks for the info 🙂 
I'll run some additional tests in the next few days and update this PR where necessary, then merge it.

**Review by sanderginn — APPROVED** [review]
I've ran tests with the `networking` and `docker-mirror` modules, and those have no qualms with `null` values for the `Name` tag. Hooray for AWS inconsistency I guess 🤷‍♂️ 

Thanks for your work @hutson, I'll merge this now 👍

**Comment by sanderginn** [comment]
@hutson this fix is now released in patch 5.1.1

**Pull request merged**
